name: max
description: "A Fashion App "

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1


dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  ionicons: ^0.2.2
  flutter_gap: ^1.2.0
  flutter_credit_card: ^4.1.0
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  supabase_flutter: ^2.9.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/mylogo.png"
  min_sdk_android: 21


flutter:


  uses-material-design: true

 
  assets:
     - assets/cover/
     - assets/logo/
     - assets/product/
     - assets/svgs/
     - assets/texts/
     - assets/pop/
     - assets/data/
    
     



  fonts:
     - family: Tenor_Sans
       fonts:
        - asset: assets\fonts\Tenor_Sans\TenorSans-Regular.ttf
        

