create table if not exists public.home_content (
  id bigint generated by default as identity primary key,
  cover_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.home_content enable row level security;

create policy "Anyone can view active home content"
on public.home_content
for select
using (is_active = true);

insert into public.home_content (cover_url, is_active)
values (null, true);
