-- ============================================================
-- Collections Schema
-- ============================================================
-- Creates the collections system: collections, collection_categories,
-- storage bucket, and RLS policies.
-- ============================================================

-- ============================================================
-- 1. Collections Table
-- ============================================================

CREATE TABLE IF NOT EXISTS public.collections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  image_url TEXT,
  display_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 2. Collection-Categories Junction Table
-- ============================================================

CREATE TABLE IF NOT EXISTS public.collection_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id BIGINT NOT NULL REFERENCES public.collections(id) ON DELETE CASCADE,
  category_id INT NOT NULL REFERENCES public.categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(collection_id, category_id)
);

-- ============================================================
-- 3. Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_collections_display_order
  ON public.collections (display_order);

CREATE INDEX IF NOT EXISTS idx_collections_is_active
  ON public.collections (is_active);

CREATE INDEX IF NOT EXISTS idx_collection_categories_collection_id
  ON public.collection_categories (collection_id);

CREATE INDEX IF NOT EXISTS idx_collection_categories_category_id
  ON public.collection_categories (category_id);

-- ============================================================
-- 4. Updated_at Trigger
-- ============================================================

CREATE OR REPLACE FUNCTION public.handle_collections_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS collections_updated_at ON public.collections;
CREATE TRIGGER collections_updated_at
  BEFORE UPDATE ON public.collections
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_collections_updated_at();

-- ============================================================
-- 5. Row Level Security
-- ============================================================

ALTER TABLE public.collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_categories ENABLE ROW LEVEL SECURITY;

-- Collections: Anyone can view active collections
CREATE POLICY "Anyone can view active collections"
  ON public.collections
  FOR SELECT
  USING (is_active = true);

-- Collection Categories: Anyone can view collection-category relationships
CREATE POLICY "Anyone can view collection categories"
  ON public.collection_categories
  FOR SELECT
  USING (true);

-- ============================================================
-- 6. Storage Bucket — collection-images
-- ============================================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('collection-images', 'collection-images', true)
ON CONFLICT (id) DO NOTHING;

-- Public read access
DROP POLICY IF EXISTS "Collection images are publicly viewable" ON storage.objects;
CREATE POLICY "Collection images are publicly viewable"
  ON storage.objects
  FOR SELECT
  TO anon, authenticated
  USING (bucket_id = 'collection-images');

-- Service role only for writes (managed via dashboard/migrations)
DROP POLICY IF EXISTS "Service role manages collection images" ON storage.objects;
CREATE POLICY "Service role manages collection images"
  ON storage.objects
  FOR ALL
  TO service_role
  USING (bucket_id = 'collection-images')
  WITH CHECK (bucket_id = 'collection-images');

-- ============================================================
-- 7. Seed Collections
-- ============================================================

-- Primary 6 collections (display_order 1-6, active)
INSERT INTO public.collections (name, image_url, display_order, is_active) VALUES
  ('Tops Collection', NULL, 1, true),
  ('Denim Edit', NULL, 2, true),
  ('Shoes Collection', NULL, 3, true),
  ('Bags Collection', NULL, 4, true),
  ('Jewelry Collection', NULL, 5, true),
  ('Dresses & Skirts', NULL, 6, true);

-- Future collections (display_order 7-10, inactive by default)
INSERT INTO public.collections (name, image_url, display_order, is_active) VALUES
  ('Shorts Collection', NULL, 7, false),
  ('Palazzo Edit', NULL, 8, false),
  ('Watches', NULL, 9, false),
  ('Sunglasses', NULL, 10, false);

-- ============================================================
-- 8. Seed Collection-Category Relationships
-- ============================================================

-- Tops Collection (id 1): T-Shirts(7), Polos(4), Shirts(5), Blouses(18), Crop Tops(19)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (1, 7), (1, 4), (1, 5), (1, 18), (1, 19);

-- Denim Edit (id 2): Jeans(3)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (2, 3);

-- Shoes Collection (id 3): Sneakers(11), Running Shoes(10), Boots(8), Loafers(9), Heels(23)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (3, 11), (3, 10), (3, 8), (3, 9), (3, 23);

-- Bags Collection (id 4): Bags(17)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (4, 17);

-- Jewelry Collection (id 5): Bracelets(13), Earrings(14), Necklaces(15), Rings(16)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (5, 13), (5, 14), (5, 15), (5, 16);

-- Dresses & Skirts (id 6): Dresses(20), Skirts(21)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (6, 20), (6, 21);

-- Shorts Collection (id 7): Shorts(6)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (7, 6);

-- Palazzo Edit (id 8): Palazzo Pants(22)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (8, 22);

-- Watches (id 9): Watches(2)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (9, 2);

-- Sunglasses (id 10): Sunglasses(1)
INSERT INTO public.collection_categories (collection_id, category_id) VALUES
  (10, 1);
